### PR TITLE
Fixes #354

### LINKED ISSUE #354: [FEATURE REQUEST] Don't send zero temperature/hum after reboot
# Feature Request

### Describe the solution / feature you'd like

After every(?) reboot Awtrix sends zero temperature and humidity to MQTT. Is it possible to send any other value instead? Like Not available?

### Describe alternatives you've considered

As a workaround, I can use fitler in Home Assistant to filter these values.
### Additional context

image

### PR DESCRIPTION
**Pull request by luebbe**
- Delay sending of stats until batt/temp/hum have been read at least once

### CODE REVIEW

**Comment by RDG88** [comment]
I've built a custom AWTRIX without a battery, temperature, and humidity sensor.

Following the documentation, I set up my dev.json with these values:

```json
{
  "matrix": "2",
  "sensor_reading": false
}
```
This configuration turns off the readings for the temperature and humidity sensors, but it does not affect the battery reading.

Following these changes, the MQTT 'stats' topic no longer receives updates. Also, sensor data updates are absent in the MQTT topic used by Home Assistant.

I suspect the issue arises from the absence of a battery in my custom-built AWTRIX. Given that some users operate their Ulanzi devices without batteries, this should be addressed.

**Comment by Blueforcer** [comment]
Seems to be a problem with the range validation:
https://discord.com/channels/546407049148366859/1090963706126553179/1179510622224920706

**Comment by luebbe** [comment]
It's not the range check.
I thought I had taken care of this by setting SENSORS_STABLE to true in the else case of the awtrix2_upgrade define. But I see that there is a way past it, when you build with the ESP32_S3 environment. @RDG88 which environment do you use for your build?
Or do you just flash the existing ulanzi binary? It may make sense to add a define or a setting that turns off battery reading.

**Comment by RDG88** [comment]
@luebbe I just use the official released Ulanzi binary found @ https://github.com/Blueforcer/awtrix-light/releases/download/0.91/ulanzi_TC001_0.91.bin

**Pull request merged**
