### PR TITLE
Fixing DFplayer not playing MP3 files

### PR DESCRIPTION
**Pull request by robercy**
This PR fix the DFplayer not playing MP3 files.

### CODE REVIEW

**Comment by Blueforcer** [comment]
Whats the reason for this PR?
Currently it works perfectly for users with DFplayer.
Changing a whole lib, and remove the possibility to update the EasyButton lib should cause in an deeper explaination :)

**Comment by robercy** [comment]
Hello!

In fact, using DFplayers chinese clones, like this one [https://pt.aliexpress.com/item/32657798948.html?spm=a2g0o.order_detail.order_detail_item.3.d3894c7fboY1Lf&gatewayAdapt=glo2bra](url), MFMiniMp3 must use checksums, and this is not possible using the local lib.
About EasyButton, I force use the 2.0.1 version, because the latest one has a problem with Filter.h compilation, see this  [https://github.com/evert-arias/EasyButton/issues/83](url), after fixed we can remove this constraint from platformio.ini

By the way, thanks by your great job on Awtrix Light.

**Comment by Blueforcer** [comment]
I used the noChecksum lib, because i had DFplayer clones wich doesnt work with :)
now we have a problem ;)

**Comment by robercy** [comment]
Hello.

"Chinese tech always lead us to crossroads"

If this is only with me, then you can let this way, my friend. Don´t worry.
But to keep this great awtrix bullet proof, maybe you can let the user choice, like you did with Display type. Example: If DFplayer type equal 1 then use checksum, else no checksum. Just a suggestion.

**Comment by robercy** [comment]
Please, can you inform the chipset used on MP3 DFplayer  that you use ?

**Comment by robercy** [comment]
Solved.

**Comment by Blueforcer** [comment]
> Solved.

How, why?

**Comment by robercy** [comment]
I don't know. I compiled and installed the new 0.71, without my mod, and mp3 works. Still there is a 2 seconds delay between serial command and playing the mp3, but after some research, I discover this is my crappy chipset.
Anyway, thanks by your concern, and congratulations by this great job on develop awtrix.

**Comment by Blueforcer** [comment]
Mhh nothing has changed to the DFPlayer stuff the last few versions 

Anyway ,glad to hear it works now.
Maybe you should by another one:)

**Comment by robercy** [comment]
Maybe a made some mistakes before, Who knows ??
I'm researching a more reliable module. Thanks again.

**Comment by robercy** [comment]
Hello, I have news from this problem.

After unstable behavior, and a lot of research, I discover (as discussed on https://github.com/ghmartin77/DFPlayerAnalyzer/issues/10) the final solution: On my case, changing the value of c_msSendSpace to 200 (line 365 on DFMiniMp2.h file) solved my problem.

My suggestion, if possible and no cause other problem, will be change this value on next PR on github. Thanks.

**Pull request closed without merging**
