### PR TITLE
Add http basic auth

### PR DESCRIPTION
**Pull request by buglloc**
I would like to set a password for all handlers except captive portal. Feels uncomfortable that any device on my network can update the firmware, steal MQTT login/pass, etc :)

### CODE REVIEW

**Comment by Blueforcer** [comment]
Thank you for your work, everything works very well. However, my AWTRIX Light Apps no longer work with it.
The problem isn't the API request, it's the displaying of the icons in a web view. For security reasons, the web views have not supported basic authentication in the URL for a long time, e.g. **http://username:password@192.168.178.101/ICONS/1213.jpg**
Therefore, with this integration, the app cannot be used to its full extent.
I need to figure out how to solve this problem

**Comment by buglloc** [comment]
I'm not a mobile app developer at all, but I think there should be a way to add support for basic auth or a custom request header :)
For example Android WebView: https://github.com/buglloc/awtrix-auth-test/blob/main/app/src/main/java/com/example/app/MyWebViewClient.java#L31-L40



I can try to add support to applications too, if you show some example of how they work. Do I understand correctly that they are proprietary and closed-source?

**Comment by Blueforcer** [comment]
i dont said its impossible, just need to figure it out, since im not using native language.
As soon as i find time for that i will merge this PR.

Yes iOS and Android is closed-source

**Comment by Blueforcer** [comment]
ok easier than i thought
```
Sub WebView1_UserAndPasswordRequired (Host As String, Realm As String) As String()
 Return Array As String("username", "password")
End Sub
```

**Comment by Blueforcer** [comment]
ok, so your example works,
unfortunally not with direct request of icons, like

```html
<html>
   <head>
      <meta name='viewport' content='width=device-width, initial-scale=1.0, user-scalable=no, viewport-fit=cover'>
      <style>
         body, html { margin: 0; padding: 0; overflow: auto; background-color: black; }
         .icon-container { display: flex; flex-wrap: wrap; justify-content: center; width: 100%; }
         .icon-footer { text-align: center; color: white; font-size: 14px; height: 20px; }
         .icon { width: 25%; height: calc(25vw + 20px); padding: 10px; box-sizing: border-box; display: flex; flex-direction: column; align-items: center; justify-content: space-between; }
         img { width: 100%; object-fit: cover; image-rendering: pixelated; cursor: pointer; }
      </style>
   </head>
   <body>
      <div class='icon-container'>
         <div class='icon'>
            <img src='http://192.168.178.101/ICONS/101.jpg' onclick='window.location.href="101.jpg"' />
            <div class='icon-footer'>101</div>
         </div>
      </div>
   </body>
</html>
```

**Comment by Blueforcer** [comment]
got it, another API request before loading the icon html works

**Pull request merged**
