### PR TITLE
implement deep sleep

### PR DESCRIPTION
**Pull request by ejalal**
Please review and accept if it complies with your coding standard to satisfy #326 
Forgot to add a call to DisplayManager.setPower(false) in MQTTManager

### CODE REVIEW

**Comment by Blueforcer** [comment]
Is it supposed to be that the ESP restarts after the sleep instead of just continuing to work?

**Comment by DanielHabenicht** [comment]
@ejalal one question for this mode. Is it possible to wake it up again by pressing any or a specific button?

**Comment by Blueforcer** [comment]
No, because the buttons are not connected to the necessary reset pin.

**Comment by DanielHabenicht** [comment]
Oh, that's a pity. I thought it might be possible as the ext1 interrupt on the ESP32 seems configurable. And [according to these pinouts](https://github.com/aptonline/PixelIt_Ulanzi#pinouts) the buttons are connected to RTC pins. 

But I am completely new to this, so you probably already tried it. Thanks, for the stellar response times!

**Comment by Blueforcer** [comment]
I have not tried it, is not my PR :)
But please feel free to extend it.

**Pull request merged**
