### PR TITLE
[Feature] Add basic WLED style 2D effect implementation as a native app

### PR DESCRIPTION
**Pull request by blutack**
Referencing #220, now we can have pretty effects *and* custom apps/notifications.

[effects.webm](https://github.com/Blueforcer/awtrix-light/assets/348305/8c35e340-1cb7-47d6-8668-2e3203378d19)

I've ported the "hiphotic" 2D effect from WLED as a new native "effects" app in index 6 (so after battery).

We can add more effects to the app and settings to control them (speed/intensity) down the line pretty easily if you are happy with the implementation. I would extract it out from Apps.h into it's own little module.

I've wired it through everywhere I can see requires it and it seems to work very well. Implementation was pretty simple and has almost no flash cost as there is already a FastLED dep and that's doing the heavy lifting. 
Seems to respect brightness etc, transitions work nicely. May need an additional maximum brightness limiter - I've not had any issues with my Ulanzi but I don't run it at 100%.

I've defaulted it to "on" but possibly you wouldn't want it that way for shipping defaults - it's pretty eye catching.

Thanks for all your hard work on awtrix and hope you can consider accepting this PR, or at least something like it!

### CODE REVIEW

**Comment by Blueforcer** [comment]
Sorry for the late response.

Wouldnt it better to use it as an API call? Like the moodlight?
I think most people doesnt want to have it in the loop, so the user can control when to show. Like you said as screensaver or notification.

This also gives the freedom to parse some parameters.
How you want to configure it, if its a fixed app?

**Comment by blutack** [comment]
Not a problem at all, we're all busy and I appreciate your time!

I could potentially add it in like moodlight if you like but that doesn't integrate as nicely. From my testing, notifications don't work (well, are hidden behind the moodlight). Once the moodlight is on, only an empty post request will disable it again. Sending API requests for app switching etc doesn't work.

Also, I have mine configured with auto transitions disabled but some of the built in apps active, so I can scroll to them if necessary or I want to check something. In future, if I add any custom apps it might be nice to scroll to them or at least trigger them as well via the API.

Configuration-wise I was imagining doing it similarly to the existing built in apps, such as timer and alarm, by adding a dedicated POST & MQTT endpoint (either with or without persistence). The effects would also map pretty easily through using the existing HA autodiscovery as that has full support for displaying a list of effects and settings.

Alternatively, it could be implemented with keys on the /settings endpoint like the way the clock and calendar appearances are configured.

 I could potentially fix all this mood light stuff but at the end of the day the best way might be just to integrate it into the excellent already existing UI design of the apps!

It is your project at the end of the day but as a suggestion, what about adding Eyes to the Effects app as the default effect and then removing Eyes? That way we don't add any extra apps, behaviour stays the same, and I can add a /api/effects endpoint so people interested (like me) can change the Eyes effect to others?

**Comment by Blueforcer** [comment]
We've just been discussing this :-) You're correct in saying that the Moodlight and Eyes features are practically identical. it's just grown hiostorically and I didn't consider that at that moment of development. They would integrate well with the 2D effect functionalities. This leads me to propose an idea. Instead of one native "effect app", we could (like you said) remove the Moodlight API and Eyes app ad add them into a separate 'effects.h' file, also incorporating all the 2D features. With a few modifications, it could be feasible to call each effect function from any custom app or notification. So you could have multiple different "effects apps" rather than a single one, and on the other hand, you can also call these apps through the API just like native apps (wich is already possible). Also youre able to use the effect as a background and draw text over it.
Do you see it differently? or do you see any disadvantages to this idea?
For me Awtrix light already has too much native apps and with eyes it doesnt follow the base idea anymore. This was my fault xD

**Comment by blutack** [comment]
I think that's an excellent suggestion! Effectively, you would move the effects to a "background" layer - which would allow for some very neat displays. It may be worth adding a "blank" native app as well - or it could be done as a custom app, although that would make it harder for less technical users to use the effects.

Did you want me to sketch out the proposed design more solidly or just implement something and you can have a look?

Oh, and I couldn't resist a quick mock up (literally just calling EffectsApp at the start of TimeApp)...

[clock_bg.webm](https://github.com/Blueforcer/awtrix-light/assets/348305/aca0e03d-806c-4ed8-ad4a-a63ade6f0019)

**Comment by Blueforcer** [comment]
For sure the community will create easy to use automations and helper vor several smarthome systems to call them easily. Like already done for complete customapp creations.
And if we also want to use it as backgroundlayer (Wich looks pretty good btw) its would not a problem.
Since im currently change some smaller things here and there i would kindly ask you to write the effects.h and push it to the beta branch.
When im finish with my changes i would start to implement it for customapps, notifications and as a optional backgroundlayer. 
Otherwise merging will be a horror for me xD
Is that ok for you? Maybe you can join my discord server and we can go deeper together :)

**Comment by blutack** [comment]
Sounds like a good plan, I've found the discord if you want to discuss it further?

**Comment by blutack** [comment]
I'm going to close this out and resubmit an effects module against the beta branch as discussed on discord.

**Pull request closed without merging**
