### PR TITLE
various minor improvements

### PR DESCRIPTION
**Pull request by tmonjalo**
While working on a new feature, I did few small improvements shared here.

### CODE REVIEW

**Comment by Blueforcer** [comment]
Most of the beta testers get a bootloop.
it looks like it happens in the modified time app

 ```
 #0  0x4008bc25:0x3ffb20c0 in __strftime at /builds/idf/crosstool-NG/.build/HOST-x86_64-w64-mingw32/xtensa-esp32-elf/src/newlib/newlib/libc/time/strftime.c:1022
  #1  0x4008c199:0x3ffb2130 in strftime at /builds/idf/crosstool-NG/.build/HOST-x86_64-w64-mingw32/xtensa-esp32-elf/src/newlib/newlib/libc/time/strftime.c:1445
  #2  0x400d459d:0x3ffb2150 in TimeApp(FastLED_NeoMatrix*, MatrixDisplayUiState*, short, short, GifPlayer*) at src/Apps.cpp:119
  #3  0x400e5801:0x3ffb21c0 in MatrixDisplayUi::drawApp() at src/MatrixDisplayUi.cpp:420
  #4  0x400e585b:0x3ffb21e0 in MatrixDisplayUi::tick() at src/MatrixDisplayUi.cpp:245
  #5  0x400e5935:0x3ffb2200 in MatrixDisplayUi::update() at src/MatrixDisplayUi.cpp:195
  #6  0x400df6f4:0x3ffb2230 in DisplayManager_::tick() at src/DisplayManager.cpp:1193
  #7  0x400ee0c7:0x3ffb2270 in loop() at src/main.cpp:107
  #8  0x40101499:0x3ffb2290 in loopTask(void*) at C:/Users/Micro/.platformio/packages/framework-arduinoespressif32/cores/esp32/main.cpp:50
```

wich points me to
image

**Comment by Blueforcer** [comment]
Edit seems like this workaround does the trick

**Comment by tmonjalo** [comment]
Which workaround?

**Comment by Blueforcer** [comment]
No worries, I've fixed it

**Pull request merged**
